name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: pwd
      run: docker build "part-a-weather-api" --file "part-a-weather-api/Dockerfile" --tag weather-api-image:$(date +%s)
